#!/usr/bin/env python3
"""Pack this repo and its Python dependencies for a machine with no internet.

  python tools/offline_kit.py --out kit/ [--platform manylinux2014_x86_64] [--python-version 3.11] [--with-dotagents]
Writes into --out: pmcro.bundle (git bundle of all refs), wheelhouse/ (pinned wheels), INSTALL.md,
SHA256SUMS. --platform is a pip platform tag for the TARGET machine (win_amd64, macosx_14_0_arm64,
manylinux2014_x86_64); --python-version must match the target's Python. --with-dotagents also packs
node_modules for @sentry/dotagents (needs npm). Needs internet on THIS machine only.
Output: a summary line per artifact; exit 1 if any download fails. Makes no model calls.
Model weights are NOT included: copy Ollama models separately (see docs/offline-kit.md).
"""
import argparse, hashlib, pathlib, subprocess, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
# Exact == pins permit the one prerelease (agent-framework-ollama) without a global --pre, which would
# also pull prerelease transitive dependencies (a real bug the offline install test caught).
# Pinned to the versions CI and the docs were verified with.
REQUIREMENTS = ["pyyaml==6.0.2", "agent-framework-core==1.19.0", "agent-framework-ollama==1.0.0b260813", "mcp==1.28.1"]
DOTAGENTS = "@sentry/dotagents@3.2.0"


def sh(*cmd, cwd=None):
    r = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    if r.returncode:
        sys.exit(f"FAIL: {' '.join(cmd[:4])} ...\n{r.stdout[-800:]}{r.stderr[-800:]}")
    return r.stdout


def sha256(p):
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def main():
    a = argparse.ArgumentParser()
    a.add_argument("--out", required=True)
    a.add_argument("--platform", default="manylinux2014_x86_64")
    a.add_argument("--python-version", default="3.11")
    a.add_argument("--with-dotagents", action="store_true")
    a = a.parse_args()
    out = pathlib.Path(a.out).resolve()
    (out / "wheelhouse").mkdir(parents=True, exist_ok=True)
    if sh("git", "status", "--porcelain", cwd=ROOT).strip():
        print("WARN: uncommitted changes are NOT in the bundle; commit first")
    sh("git", "bundle", "create", str(out / "pmcro.bundle"), "--all", cwd=ROOT)
    print("ok: pmcro.bundle")
    sh(sys.executable, "-m", "pip", "download", "--dest", str(out / "wheelhouse"), "--only-binary=:all:",
       "--platform", a.platform, "--python-version", a.python_version, "--implementation", "cp", *REQUIREMENTS)
    print(f"ok: wheelhouse for {a.platform} / Python {a.python_version}")
    if a.with_dotagents:
        sh("npm", "install", DOTAGENTS, "--prefix", str(out / "node"), "--no-audit", "--no-fund")
        print("ok: node/ with", DOTAGENTS)
    (out / "INSTALL.md").write_text(f"""# Offline install (generated by tools/offline_kit.py)

Target: platform `{a.platform}`, Python {a.python_version}. Wheels for another platform will not install.

1. Verify: `sha256sum -c SHA256SUMS` (on Windows compare with `Get-FileHash`).
2. `git clone pmcro.bundle pmcro` then `cd pmcro`.
3. `python -m venv .venv` and activate it.
4. `pip install --no-index --find-links ../wheelhouse {' '.join(REQUIREMENTS)}`
5. `python tools/pmcro.py validate` and `python -m unittest discover -s tests`.
6. Ollama and its model files are NOT in this kit; see docs/offline-kit.md.
""")
    files = sorted(p for p in out.rglob("*") if p.is_file() and "node" not in p.relative_to(out).parts[:1] and p.name != "SHA256SUMS")
    (out / "SHA256SUMS").write_text("".join(f"{sha256(p)}  {p.relative_to(out)}\n" for p in files))
    print(f"ok: SHA256SUMS ({len(files)} files)")


if __name__ == "__main__":
    main()
