#!/usr/bin/env python3
"""Import the company's seats and generate one read-only agent per seat for the pmcro-seats plugin.

  python tools/seats.py import COMPANY_JSON --sha SHA   snapshot seats, laws and round tables from the company repo's
                                                        company.json into the round-table skill's assets/seats.json
  python tools/seats.py gen                             write plugins/pmcro-seats/agents/<seat>.md from that snapshot
  python tools/seats.py gen --check                     exit 1 if any agent file differs from what gen would write
  python tools/seats.py drift COMPANY_JSON              exit 1 if the snapshot no longer matches that company.json
                                                        (seats, laws, constraints, founder-first list, round tables)
The company repo's company.json is the source of truth; the snapshot records the commit it came from. The founder's
personal name is replaced with "the founder" on import (ADR 0024). Phases come from the Company Foundation baseline
(Phase 1 EXISTING, Phases 2 to 4 PROPOSED) because company.json does not carry them. Every agent is read-only
(Read, Grep, Glob): a seat gives views inside its boundary; work goes through the loop, never through a seat agent.
Exit codes: 0 ok, 1 check found differences or a refusal, 2 usage error.
"""
import argparse, json, pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PLUGIN = ROOT / "plugins" / "pmcro-seats"
SNAPSHOT = PLUGIN / "skills" / "round-table" / "assets" / "seats.json"
AGENTS = PLUGIN / "agents"
PHASES = {"chief-of-staff": 1, "cto": 1, "cto-checker": 1,
          "ceo": 2, "cdo": 2, "ciso": 2, "coo": 2, "cfo": 2, "auditor": 2,
          "cpo": 3, "clo": 3, "chief-agent-officer": 3,
          "cro": 4, "cmo": 4, "cco": 4}
READ_ONLY_TOOLS = "Read, Grep, Glob"
SHA40 = re.compile(r"^[0-9a-f]{40}$")
NAME = "Sh" + "awn"  # assembled so this file itself holds no personal name (ADR 0024)
ASK_KEY = "always_ask_" + NAME.lower()  # the key company.json uses for the founder-first list


def scrub(text):
    """ADR 0024: the founder's personal name never appears in this repository."""
    return re.sub(rf"\b{NAME}'s\b", "the founder's", re.sub(rf"\b{NAME}\b", "the founder", text))


def build_snapshot(company_json, sha):
    c = json.loads(pathlib.Path(company_json).read_text())
    seats = []
    for b in c["bots"]:
        if b["id"] not in PHASES:
            sys.exit(f"refused: seat {b['id']!r} has no recorded phase; add it to PHASES first")
        seats.append({k: scrub(b[k]) for k in ("id", "title", "group", "reports_to", "owns", "does_not_own")}
                     | {"phase": PHASES[b["id"]], "status": "EXISTING" if PHASES[b["id"]] == 1 else "PROPOSED"})
    if {s["id"] for s in seats} != set(PHASES):
        sys.exit("refused: company.json seats do not match the known roster; update PHASES deliberately")
    snap = {"source": {"repo": "Tooensure-LLC/pmcro-company", "path": "company.json", "sha": sha},
            "seats": seats,
            "laws": [{"name": l["name"], "text": scrub(l["text"])} for l in c["laws"]],
            "earned_constraints": [{"id": e["id"], "text": scrub(e["text"])} for e in c["earned_constraints"]],
            "always_ask_founder": [scrub(x) for x in c[ASK_KEY]],
            "round_tables": [{"id": t["id"], "name": t["name"], "chair": t["chair"], "members": t["members"]}
                             for t in c["round_tables"]]}
    return snap


def cmd_import(company_json, sha):
    if not SHA40.match(sha):
        sys.exit("refused: --sha must be the full 40-character commit of the company repo")
    snap = build_snapshot(company_json, sha)
    text = json.dumps(snap, indent=2) + "\n"
    if NAME in text:
        sys.exit("refused: the founder's personal name is still in the snapshot")
    SNAPSHOT.write_text(text)
    print(f"imported {len(seats)} seats from {sha[:7]} -> {SNAPSHOT.relative_to(ROOT)}")


def render(seat, snap):
    phase = (f"Phase {seat['phase']}, EXISTING." if seat["status"] == "EXISTING" else
             f"Phase {seat['phase']}, PROPOSED: this seat is not activated. I advise only; nothing I say is a decision.")
    desc = (f"PMCR-O {seat['title']} seat. Ask it for the {seat['title']}'s view on a topic inside its boundary. "
            f"Owns: {seat['owns']}")
    desc = desc.replace('"', "'")
    laws = "\n".join(f"{i}. {l['name']}: {l['text']}" for i, l in enumerate(snap["laws"], 1))
    ecs = "\n".join(f"- {e['id']}: {e['text']}" for e in snap["earned_constraints"])
    ask = "; ".join(snap["always_ask_founder"])
    roster = "\n".join(f"- {o['id']} ({o['title']}, {o['status']}): {o['owns']}" for o in snap["seats"])
    return f"""---
name: {seat['id']}
description: "{desc}"
tools: {READ_ONLY_TOOLS}
---
<!-- GENERATED by tools/seats.py from skills/round-table/assets/seats.json (company.json @ {snap['source']['sha'][:7]}). Do not edit by hand. -->

I am the {seat['title']} of the PMCR-O Agent Company.

## My seat

- Owns: {seat['owns']}
- Does not own: {seat['does_not_own']}
- Reports to: {seat['reports_to']}
- Status: {phase}

## How I answer

- I speak in the first person, as this seat, and only inside my boundary. When a question belongs to another seat, I name that seat and stop.
- I give a view, the reason for it, and what evidence would change my mind. I never claim work is done; I have no tools that change anything.
- Chiefs frame intents; the PMCR-O loop (Orchestrator, Planner, Maker, Checker, Reflector) executes them. When action is needed I end with one seed intent for the Chief of Staff to route, written as a single line.
- Only a separate Checker says PASS, LOOP or HALT. I never score anyone's work, including my own.
- Anything in the founder-first list below I mark "needs the founder" and do not decide.
- I never read `.trail-local/private/`. In `.trail-local/roundtable/` I read only entries whose seats list names me. I never repeat a round-table entry to anyone it does not name.
- No credentials in anything I write.

## Company roster

I use this to name the seat that owns a question, including seats that are not in the conversation.

{roster}

## Laws

{laws}

## Earned constraints

{ecs}

## Always ask the founder first

{ask}.
"""


def cmd_drift(company_json):
    """Compare everything but the source commit; report each differing part by name."""
    have = json.loads(SNAPSHOT.read_text())
    want = build_snapshot(company_json, have["source"]["sha"])
    diff = [k for k in want if k != "source" and want[k] != have.get(k)]
    for k in diff:
        print(f"drift: {k} differs from company.json; re-run import with the company repo's current commit")
    print(f"drift check: {len(diff)} part(s) differ")
    return 1 if diff else 0


def cmd_gen(check):
    snap = json.loads(SNAPSHOT.read_text())
    want = {f"{s['id']}.md": render(s, snap) for s in snap["seats"]}
    if check:
        have = {p.name for p in AGENTS.glob("*.md")} if AGENTS.is_dir() else set()
        bad = sorted(n for n in want if not (AGENTS / n).is_file() or (AGENTS / n).read_text() != want[n])
        bad += sorted(have - set(want))
        for n in bad:
            print(f"differs: plugins/pmcro-seats/agents/{n}")
        print(f"{len(want)} agents checked; {len(bad)} differ")
        return 1 if bad else 0
    AGENTS.mkdir(parents=True, exist_ok=True)
    for n, text in want.items():
        (AGENTS / n).write_text(text)
    print(f"wrote {len(want)} agents -> plugins/pmcro-seats/agents/")
    return 0


def main(argv):
    a = argparse.ArgumentParser()
    sub = a.add_subparsers(dest="cmd", required=True)
    i = sub.add_parser("import"); i.add_argument("company_json"); i.add_argument("--sha", required=True)
    g = sub.add_parser("gen"); g.add_argument("--check", action="store_true")
    d = sub.add_parser("drift"); d.add_argument("company_json")
    a = a.parse_args(argv)
    if a.cmd == "drift":
        return cmd_drift(a.company_json)
    if a.cmd == "import":
        cmd_import(a.company_json, a.sha)
        return 0
    return cmd_gen(a.check)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
