"""Generate site/plugins.md, the docs-site plugin catalog, from .claude-plugin/marketplace.json.

Usage: python tools/site_catalog.py gen            writes site/plugins.md
       python tools/site_catalog.py gen --check    exits 1 if site/plugins.md is stale (CI uses this)
The marketplace manifest is the source of truth; the page is generated so it can never drift (ADR 0031).
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / ".claude-plugin" / "marketplace.json"
OUT = ROOT / "site" / "plugins.md"


def render():
    """Return the catalog page text built from the marketplace manifest, plugins in manifest order."""
    data = json.loads(MANIFEST.read_text(encoding="utf-8"))
    name = data.get("name", "pmcro-plugins")
    own = [p for p in data["plugins"] if str(p.get("source", "")).startswith("./plugins/")]
    pinned = [p for p in data["plugins"] if p not in own]
    lines = [
        "---",
        "title: Plugin catalog",
        "---",
        "",
        "<!-- Generated by tools/site_catalog.py from .claude-plugin/marketplace.json. Do not edit by hand. -->",
        "",
        "# Plugin catalog",
        "",
        f"Every plugin in the `{name}` marketplace. Add the marketplace once, then install by name:",
        "",
        "```",
        "/plugin marketplace add Tooensure-LLC/pmcro",
        f"/plugin install <plugin>@{name}",
        "```",
        "",
        f"## PMCR-O plugins ({len(own)})",
        "",
        "| Plugin | What it does |",
        "| --- | --- |",
    ]
    lines += [f"| `{p['name']}` | {p.get('description', '').replace('|', '/')} |" for p in own]
    if pinned:
        lines += [
            "",
            f"## Pinned upstream plugins ({len(pinned)})",
            "",
            "Listed from [dotnet/skills](https://github.com/dotnet/skills) at a pinned commit, not copied (ADR 0004).",
            "",
            "| Plugin | What it does |",
            "| --- | --- |",
        ]
        lines += [f"| `{p['name']}` | {p.get('description', '').replace('|', '/')} |" for p in pinned]
    lines += ["", "Status: CANDIDATE. Each plugin's own README states what was and was not tested.", ""]
    return "\n".join(lines)


def main(argv):
    """Write the page, or with --check compare it and exit 1 when stale."""
    if len(argv) < 2 or argv[1] != "gen":
        print(__doc__)
        return 2
    text = render()
    if "--check" in argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print("site/plugins.md is stale; run: python tools/site_catalog.py gen")
            return 1
        print("site/plugins.md is up to date")
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
