"""Generate the docs site's derived files so they can never drift (ADR 0031, ADR 0032).

Writes two files:
  site/plugins.md     the plugin catalog, from .claude-plugin/marketplace.json
  site/docs/toc.yml   the docs sidebar, from the curated page list in site/docfx.json (titles from each page's first heading)

Usage: python tools/site_catalog.py gen            writes both files
       python tools/site_catalog.py gen --check    exits 1 if either file is stale (CI uses this)
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / ".claude-plugin" / "marketplace.json"
OUT = ROOT / "site" / "plugins.md"
DOCFX = ROOT / "site" / "docfx.json"
TOC = ROOT / "site" / "docs" / "toc.yml"


def render():
    """Return the catalog page text built from the marketplace manifest, plugins in manifest order."""
    data = json.loads(MANIFEST.read_text(encoding="utf-8"))
    name = data.get("name", "pmcro-plugins")
    own = [p for p in data["plugins"] if str(p.get("source", "")).startswith("./plugins/")]
    pinned = [p for p in data["plugins"] if p not in own]
    lines = [
        "---",
        "title: Plugin catalog",
        "---",
        "",
        "<!-- Generated by tools/site_catalog.py from .claude-plugin/marketplace.json. Do not edit by hand. -->",
        "",
        "# Plugin catalog",
        "",
        f"Every plugin in the `{name}` marketplace. Add the marketplace once, then install by name:",
        "",
        "```",
        "/plugin marketplace add Tooensure-LLC/pmcro",
        f"/plugin install <plugin>@{name}",
        "```",
        "",
        f"## PMCR-O plugins ({len(own)})",
        "",
        "| Plugin | What it does |",
        "| --- | --- |",
    ]
    lines += [f"| `{p['name']}` | {p.get('description', '').replace('|', '/')} |" for p in own]
    if pinned:
        lines += [
            "",
            f"## Pinned upstream plugins ({len(pinned)})",
            "",
            "Listed from [dotnet/skills](https://github.com/dotnet/skills) at a pinned commit, not copied (ADR 0004).",
            "",
            "| Plugin | What it does |",
            "| --- | --- |",
        ]
        lines += [f"| `{p['name']}` | {p.get('description', '').replace('|', '/')} |" for p in pinned]
    lines += ["", "Status: CANDIDATE. Each plugin's own README states what was and was not tested.", ""]
    return "\n".join(lines)


def _title(path):
    """Return the page's first level-1 heading, or its file name when it has none."""
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return path.stem


def _yaml_str(text):
    """Quote a string for YAML so colons, quotes and leading symbols stay literal."""
    return json.dumps(text, ensure_ascii=False)


def render_toc():
    """Return site/docs/toc.yml: the curated docs pages named in site/docfx.json, grouped as guides, product and decisions."""
    config = json.loads(DOCFX.read_text(encoding="utf-8"))
    entry = next(c for c in config["build"]["content"] if c.get("src") == "../docs")
    src = (DOCFX.parent / entry["src"]).resolve()
    pages = []
    for pattern in entry["files"]:
        pages += sorted(src.glob(pattern)) if any(ch in pattern for ch in "*?[") else [src / pattern]
    rel = lambda p: "../../docs/" + p.relative_to(src).as_posix()
    groups = {"Guides": [], "Product": [], "Decision records": []}
    for p in pages:
        key = p.relative_to(src).parts[0]
        group = "Decision records" if key == "decisions" else "Product" if key == "product" else "Guides"
        groups[group].append(p)
    lines = ["# Generated by tools/site_catalog.py from the page list in site/docfx.json. Do not edit by hand.",
             "- name: Overview", "  href: index.md"]
    for group, items in groups.items():
        if not items:
            continue
        lines += [f"- name: {_yaml_str(group)}", "  items:"]
        for p in items:
            title = _title(p)
            if group == "Decision records":
                title = re.sub(r"^(\d{4}):\s*", r"\1 · ", title)
            lines += [f"  - name: {_yaml_str(title)}", f"    href: {rel(p)}"]
    return "\n".join(lines) + "\n"


def main(argv):
    """Write the page, or with --check compare it and exit 1 when stale."""
    if len(argv) < 2 or argv[1] != "gen":
        print(__doc__)
        return 2
    outputs = {OUT: render(), TOC: render_toc()}
    if "--check" in argv:
        stale = [p for p, text in outputs.items() if (p.read_text(encoding="utf-8") if p.exists() else "") != text]
        for p in stale:
            print(f"{p.relative_to(ROOT).as_posix()} is stale; run: python tools/site_catalog.py gen")
        if not stale:
            print("site/plugins.md and site/docs/toc.yml are up to date")
        return 1 if stale else 0
    for p, text in outputs.items():
        p.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {p.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
